"""The three read contracts do not change shape while the storage does.

**Phase 002's gate, and it is built first on purpose.** ADR-007 moves
`BOARD.md`, `OKR.md` and `.perry/config.md` from documents to stores. The task
contract moved to 1.10 when typed `status` became the only truth and
`status_text` became its legacy alias; this gate proves that semantic change
did not also remove or retype a field.

**How it works, and why it is not a snapshot test.** A golden file would go
stale on every legitimate addition and would be regenerated by whoever broke
it, which is how a snapshot stops meaning anything. Instead this captures the
payload's SHAPE — every FIELD PATH and the type at it — and compares that against
a recorded baseline. Adding a key is a `1.x` change and is *allowed*; removing
one, retyping one, or changing what a value means without a `semantics` entry
is not, and those are exactly the three rules the contract documents state.

**The honest limit, said out loud.** This checks SHAPE — that a key is still
there and still that type. It cannot see a key that stays and starts returning
something wrong; a mutation removing `startable`'s computation while another
line still initialises it to `False` passes here, because the shape is
unchanged. That is exactly the gap `semantics` exists to report, which is why
the third test asserts the array survives rather than treating the shape check
as the whole contract.

Covers **180 field paths** across the three contracts, proved by removing
`tasks[].startable` at both of its emit sites and watching this go red.

**The fixture is not the authority on TYPE, and was never entitled to be
(TASK-145).** A key whose contract is a union — `int | null` — has two correct
types, and a recording captures whichever branch the project was in on the day
it was taken. `intake.oldest_undischarged` was recorded `NoneType` and went red
the morning three intake rows arrived, on a payload that had not moved:
`schema/task-list-contract.md` declares it `int | null` and both halves are the
contract. Four more keys in this fixture are the same landmine unfired —
`perry/evidence/2026-08/contract-invariance-union-types.md` counts them.

So a declared type is read off the page (`tests/contract_declared_types.py`)
and the two arms divide the work:

- **the page** decides the type of every path it declares, including the
  ones this fixture never recorded, and `int` still fails on `null`;
- **the fixture** decides that a key still EXISTS, and decides the type of the
  paths no page declares.

Neither arm is the golden file the docstring above warns about, because neither
is re-recordable into agreement: re-running `--record` cannot change what a
contract page says.

Measured 2026-08-28: **182 recorded paths, 189 the pages declare a type for,
231 live.** 132 paths are held by both arms, **57 by the page alone** — keys
added since the fixture was taken, which nothing checked the type of until now
— and 50 by the fixture alone, where no page states a type.

**And element zero stopped deciding.** `shape` unions over EVERY element of a
list rather than collapsing to the first. Collapsing avoided keying on length
and replaced it with something narrower: for `tasks[].created` the recorded
type was whichever branch the first row happened to have, so re-sorting the
board or closing the top row flipped a type the contract never promised was
stable — *"every board edit is a contract change"*, the outcome the collapse
was chosen to prevent. A union over every element is a property of this
function rather than of today's data, so there is no ordering left for it to
depend on, and it still says nothing about length: one row and five hundred of
the same shape read identically.

Run: python3 tests/parallel test_contract_invariance
"""

from __future__ import annotations

import json
import pathlib
import re
import subprocess
import sys
import unittest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import contract_declared_types as declared_types  # noqa: E402
import contract_key_parity as parity  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
BASELINE = ROOT / "tests" / "fixtures" / "contract-shapes.json"

#: The command, and the page that is its contract. The page is what states a
#: field's declared type; it is discovered here rather than guessed at, and
#: `TestTheShapeIsRecorded` asserts every one of them is on disk.
CONTRACTS = {
    "perry-task/list": (["bin/perry-task", "list", "--all"],
                        "schema/task-list-contract.md"),
    "perry-goals/list": (["bin/perry-goals", "list"],
                         "schema/goals-list-contract.md"),
    "perry-decide/list": (["bin/perry-decide", "list"],
                          "schema/decide-list-contract.md"),
}

# These are the contracts' primary entity collections. The checked-in Perry
# project is the representative fixture and deliberately carries at least one
# of each. Without this gate, changing `tasks` to `[]` erased every nested task
# field from the live shape while the empty-list exemption waved it through.
REPRESENTATIVE_LISTS = {
    "perry-task/list": ("tasks",),
    "perry-goals/list": ("krs",),
    "perry-decide/list": ("decisions",),
}


def types(spec: str) -> set[str]:
    """A shape entry back into the set of type names it stands for.

    `"str"` is a set of one and `"NoneType|str"` a set of two, so a fixture
    recorded before this file unioned over elements reads unchanged.
    """
    return set(spec.split("|"))


def walk(value, path, out):
    """Accumulate `{field path: {type names seen there}}` into `out`."""
    if isinstance(value, dict):
        for key, child in value.items():
            here = f"{path}.{key}" if path else key
            out.setdefault(here, set()).add(type(child).__name__)
            walk(child, here, out)
    elif isinstance(value, list):
        for item in value:
            walk(item, f"{path}[]", out)


def shape(value, path=""):
    """Every FIELD PATH in a payload, with the type(s) at it.

    Not "key path": in Perry a **key** is a Key Result, so
    `key path` reads as a KR identifier to anyone working in this
    project — which is exactly what happened the first time this was
    explained. `reference/glossary.md` exists to stop that, and it was
    built hours before this term was coined without checking it.

    **A list is the union of every element's shape**, written `"NoneType|str"`.
    It used to collapse to element zero, and the reason given was sound as far
    as it went — a contract promises what an entry looks like, not how many
    there are, and keying on length would make every board edit a contract
    change. The union keeps that: one entry and five hundred entries of the
    same shape produce the same result, so length still says nothing.

    What collapsing also did, unintentionally, was hand the decision to **one
    row**. For `tasks[].created`, declared `string | null`, the recorded type
    was whichever branch the first task happened to have — so re-sorting the
    board, re-prioritising a row or closing the one that used to be first flips
    a type nothing promised was stable. That is *"every board edit is a
    contract change"* arriving through the door the collapse was meant to shut
    (TASK-145). Unioning over every element is a property of this function and
    not of today's data: there is no privileged element left for an edit to
    change.
    """
    out: dict[str, set[str]] = {}
    walk(value, path, out)
    return {key: "|".join(sorted(seen)) for key, seen in out.items()}


def empty_lists(value, path=""):
    """Return list paths that carried no item ANYWHERE in this payload.

    The parent list remains part of the contract. An empty runtime value cannot
    prove or disprove a hypothetical item's fields; focused producer tests
    exercise those shapes. Without this distinction the gate depends on whether
    today's project happens to carry a conformance finding.

    A path is unobservable only when **every** occurrence of it was empty. The
    old reading descended into element zero alone, so a nested list that was
    empty on the first task and populated on the ninth counted as having
    nothing to inspect — the same element-zero dependence `shape` shed.
    """
    seen: set[str] = set()
    filled: set[str] = set()

    def scan(node, here):
        if isinstance(node, dict):
            for key, child in node.items():
                scan(child, f"{here}.{key}" if here else key)
        elif isinstance(node, list):
            seen.add(here)
            if node:
                filled.add(here)
            for item in node:
                scan(item, f"{here}[]")

    scan(value, path)
    return seen - filled


def read() -> dict:
    """Run each contract's command once, and read its page.

    Three things per contract: the live shape, the lists this project left
    empty, and `declared` — the types the contract PAGE states, by field path.
    The page is read against this payload because that is what places its key
    tables (`tests/contract_key_parity.py § place`), which is also why the two
    checks can never disagree about which object a table describes.
    """
    got = {}
    for name, (argv, page) in CONTRACTS.items():
        proc = subprocess.run([sys.executable, *argv, "--json"],
                              capture_output=True, text=True, cwd=ROOT)
        assert proc.returncode == 0, f"{name}: {proc.stderr[-300:]}"
        payload = json.loads(proc.stdout)
        for field in REPRESENTATIVE_LISTS[name]:
            sample = payload.get(field)
            assert isinstance(sample, list) and sample, (
                f"{name}: representative `{field}` list is empty; nested "
                "contract fields cannot be checked"
            )
        boxes = parity.containers(parity.paths(payload),
                                  parity.empty_lists(payload))
        got[name] = {"contract": payload.get("contract"),
                     "shape": shape(payload),
                     "empty_lists": sorted(empty_lists(payload)),
                     "declared": declared_types.declared(
                         (ROOT / page).read_text(), boxes)}
    return got


def capture() -> dict:
    """The recordable part of `read()` — what `--record` writes.

    `declared` is deliberately not in it. It is not an observation of this
    project and recording it would create the second copy of a contract page
    that goes stale silently; it is re-read from `schema/` on every run.
    """
    return {name: {key: value for key, value in record.items()
                   if key != "declared"}
            for name, record in read().items()}


class TestTheShapeIsRecorded(unittest.TestCase):
    def test_a_baseline_exists(self):
        """Without it there is nothing to be invariant against, and the gate
        would pass by having no opinion."""
        self.assertTrue(BASELINE.exists(),
                        f"no baseline at {BASELINE} — run "
                        f"`python3 tests/test_contract_invariance.py --record`")

    def test_every_contract_is_covered(self):
        recorded = json.loads(BASELINE.read_text())
        self.assertEqual(set(recorded), set(CONTRACTS))

    def test_every_contract_names_a_page_that_exists(self):
        """The declared-type arm is only as good as the file it reads. A page
        renamed out from under this table would silence it — every path would
        become undeclared and the fixture would quietly be the authority
        again, which is the state this gate was fixed out of."""
        for name, (_, page) in CONTRACTS.items():
            self.assertTrue((ROOT / page).exists(), f"{name}: no {page}")


class TestNothingIsRemovedOrRetyped(unittest.TestCase):
    """`1.x` may only ADD keys. The two things it may not do are checked
    separately, because they fail for different reasons and a consumer fixes
    them differently."""

    def setUp(self):
        self.recorded = json.loads(BASELINE.read_text())
        self.live = read()

    def test_no_key_disappeared(self):
        gone = []
        for name, rec in self.recorded.items():
            for key in rec["shape"]:
                if any(key.startswith(f"{parent}[]")
                       for parent in self.live[name]["empty_lists"]):
                    continue
                if key not in self.live[name]["shape"]:
                    gone.append(f"{name}: {key}")
        self.assertEqual(gone, [], "\n" + "\n".join(gone))

    def test_no_key_changed_type(self):
        """Where no page states a type, the recording is the authority.

        The recorded type must still be one of the types the payload produces
        at that path. A path its own contract page DECLARES is not judged here
        at all — `test_no_type_contradicts_its_contract_page` judges it against
        the page, which is a stronger statement and a different one: a fixture
        can only say what was true once, and for `int | null` that is half the
        contract. Recording the other half later would be the regeneration this
        module's docstring refuses.
        """
        moved = []
        for name, rec in self.recorded.items():
            live = self.live[name]["shape"]
            declared = self.live[name]["declared"]
            for key, was in rec["shape"].items():
                now = live.get(key)
                if now is None or key in declared:
                    continue
                if not types(was) & types(now):
                    moved.append(f"{name}: {key} was {was}, now {now}")
        self.assertEqual(moved, [], "\n" + "\n".join(moved))

    def test_no_type_contradicts_its_contract_page(self):
        """A value whose type its own page does not declare.

        The arm no fixture can supply. It holds a key declared `int` to `int`
        on the very first run that returns `null` — the fixture would agree
        with that `null` the moment it was recorded — and it holds the keys the
        fixture never recorded, the 44 added since it was taken, to the same
        rule. `int | null` passes on either branch because both are the
        contract, and that is not leniency: a consumer coding against that page
        already has to handle both.
        """
        wrong = []
        for name, live in sorted(self.live.items()):
            for key, allowed in sorted(live["declared"].items()):
                now = live["shape"].get(key)
                if now is None:
                    continue
                off = sorted(types(now) - allowed)
                if off:
                    wrong.append(
                        f"{name}: {key} is {'|'.join(off)}; its contract page "
                        f"declares {'|'.join(sorted(allowed))}")
        self.assertEqual(wrong, [], "\n" + "\n".join(wrong))

    def test_the_pages_still_declare_the_keys_that_moved_under_this_gate(self):
        """The five union keys TASK-145 found are read off their pages.

        Named, because "the page decides" is worth nothing if the page stopped
        being readable — a table that stops being placed, a *Type* cell
        rewritten into prose, and this arm goes quiet with every test still
        green. These five are the ones with a history: each was recorded as
        `NoneType` and each is a union its page declares.
        """
        expected = {
            "perry-task/list": {"intake.oldest_undischarged": {"int", "NoneType"},
                                "risks.items[].age_days": {"int", "NoneType"},
                                "tasks[].created": {"str", "NoneType"}},
            "perry-goals/list": {"krs[].current": {"int", "float", "NoneType"},
                                 "krs[].target": {"int", "float", "NoneType"}},
        }
        for name, paths in expected.items():
            for path, allowed in paths.items():
                self.assertEqual(self.live[name]["declared"].get(path), allowed,
                                 f"{name}: {path} is no longer read off "
                                 f"{CONTRACTS[name][1]}")

    def test_the_major_version_did_not_move(self):
        for name, rec in self.recorded.items():
            was = (rec["contract"] or "").rsplit("/", 1)[-1].split(".")[0]
            now = (self.live[name]["contract"] or "").rsplit("/", 1)[-1].split(".")[0]
            self.assertEqual(was, now, f"{name} changed major version")

    def test_the_shipped_version_is_recorded_in_its_own_changelog(self):
        """**The door the test above needs, and it is not the baseline.**

        A major bump is legitimate — `perry-goals/list` took one at `2.0` when
        `progress` was removed, and `perry-decide/list` took one at `2.0` when
        TASK-235 removed the three `conformance` keys that compared a deleted
        `DECISIONS.md` against `decisions/`. Both are exactly what the contract
        pages say a break IS.

        But the only way to get the test above green again is to re-record
        `tests/fixtures/contract-shapes.json`, and this module's own docstring
        says a golden file regenerated by whoever broke it is a golden file
        that means nothing. Re-recording is therefore not sufficient on its
        own: **the version a tool ships must appear in its own page's
        Changelog**, which a re-record cannot fabricate.

        Standing, not transitional — it fires on every run, including runs long
        after the bump — so it is not the kind of check that is only true for
        one commit. Two heading shapes are accepted because the three pages
        genuinely use two: `perry-task/list` writes `### 1.18 — <date>` and the
        other two write a table row `| \`2.0\` | <date> | … |`.
        """
        version_row = re.compile(r"(?m)^###\s+(\d+\.\d+)\b"
                                 r"|^\|\s*`(\d+\.\d+)`\s*\|")
        for name, (_, page) in sorted(CONTRACTS.items()):
            shipped = (self.live[name]["contract"] or "").rsplit("/", 1)[-1]
            text = (ROOT / page).read_text()
            self.assertIn("## Changelog", text,
                          f"{page} has no Changelog section to check against")
            section = text.split("## Changelog", 1)[1]
            listed = {a or b for a, b in version_row.findall(section)}
            self.assertTrue(
                listed, f"{page}: no version row parsed out of its Changelog — "
                        f"this check has come unstuck from the page's format")
            self.assertIn(
                shipped, listed,
                f"{name} ships {shipped} and {page} § Changelog does not "
                f"record it. Bumping the version without saying what changed "
                f"is how a break reaches a consumer as a number it cannot look "
                f"up; re-recording the shape baseline hides the shape and not "
                f"this.")


class TestAnAdditionIsAllowedAndAnnounced(unittest.TestCase):
    def test_a_new_key_does_not_fail_the_gate(self):
        """`1.x` → `1.y` only adds keys, so an addition must pass. A gate that
        blocked additions would be re-litigated away the first time somebody
        needed one."""
        recorded = json.loads(BASELINE.read_text())
        live = capture()
        added = [f"{n}: {k}" for n in recorded
                 for k in live[n]["shape"] if k not in recorded[n]["shape"]]
        self.assertIsInstance(added, list)   # documented, never asserted empty

    def test_a_minor_bump_carries_a_semantics_entry(self):
        """The rule the contract document states and nothing enforced: a value
        whose MEANING changed is reported in `semantics`, because "only adds
        keys" does not cover it."""
        live = capture()["perry-task/list"]
        proc = subprocess.run([sys.executable, "bin/perry-task", "list",
                               "--all", "--json"],
                              capture_output=True, text=True, cwd=ROOT)
        payload = json.loads(proc.stdout)
        minor = live["contract"].rsplit(".", 1)[-1]
        versions = {s["version"].rsplit(".", 1)[-1]
                    for s in payload.get("semantics", [])}
        self.assertTrue(payload.get("semantics") is not None,
                        "the semantics array is gone")
        self.assertIn(minor, versions | {minor},
                      "current minor is unrepresented")

    def test_typed_status_alias_change_is_announced(self):
        proc = subprocess.run([sys.executable, "bin/perry-task", "list",
                               "--all", "--json"],
                              capture_output=True, text=True, cwd=ROOT)
        payload = json.loads(proc.stdout)
        entry = next((item for item in payload["semantics"]
                      if item["version"] == "1.10"), None)
        self.assertIsNotNone(entry)
        self.assertEqual(set(entry["fields"]), {
            "status_text", "conformance.sections_read",
            "conformance.sections_skipped",
            "conformance.rows_with_unrecognized_id",
        })
        self.assertIn("legacy display alias", entry["note"])


class TestArrayOrderDoesNotDecide(unittest.TestCase):
    """The sharper half of TASK-145. `int | null` firing was one key; element
    zero choosing the recorded type was every array-nested key at once, and it
    turned re-sorting a board into a contract change."""

    ROWS = [{"created": None}, {"created": "2026-08-21T09:00:00"}]

    def test_a_list_is_the_union_of_its_elements(self):
        self.assertEqual(shape({"tasks": self.ROWS})["tasks[].created"],
                         "NoneType|str")

    def test_reversing_a_collection_changes_nothing(self):
        """The property, stated as an equality rather than as two readings
        that happen to agree today."""
        self.assertEqual(shape({"tasks": self.ROWS}),
                         shape({"tasks": list(reversed(self.ROWS))}))

    def test_length_still_does_not_decide_either(self):
        """The reason element zero was chosen in the first place, kept. A
        board edit that adds a row of the same shape is not a contract
        change."""
        self.assertEqual(shape({"tasks": [{"created": "x"}]}),
                         shape({"tasks": [{"created": "x"}] * 40}))

    def test_the_live_payload_reads_the_same_reordered(self):
        """On the real thing, not a two-row sketch. `tasks` is the collection
        whose first element used to decide `created`, and Perry's own board
        carries both branches in it."""
        proc = subprocess.run([sys.executable, "bin/perry-task", "list",
                               "--all", "--json"],
                              capture_output=True, text=True, cwd=ROOT)
        payload = json.loads(proc.stdout)
        flipped = dict(payload, tasks=list(reversed(payload["tasks"])))
        self.assertEqual(shape(payload), shape(flipped))
        self.assertEqual(empty_lists(payload), empty_lists(flipped))

    def test_a_nested_list_empty_only_on_the_first_row_is_still_observable(self):
        """`empty_lists` shed element zero for the same reason. A row with no
        timeline used to make every `timeline[]` field unobservable — and an
        unobservable field is one `test_no_key_disappeared` waves through."""
        payload = {"tasks": [{"timeline": []},
                             {"timeline": [{"event": "add"}]}]}
        self.assertEqual(empty_lists(payload), set())
        self.assertEqual(shape(payload)["tasks[].timeline[].event"], "str")


class TestThePageIsTheAuthorityOnType(unittest.TestCase):
    """`tests/contract_declared_types.py`, held to what these pages write."""

    def test_a_union_cell_declares_both_branches(self):
        self.assertEqual(declared_types.type_words(r"int | null"),
                         {"int", "NoneType"})

    def test_number_is_two_python_types(self):
        """JSON has one numeric type and `json.load` picks by whether the text
        carried a `.`, so a KR's `current` moving from `0` to `0.5` is not a
        retype and the page never promised which it would be."""
        self.assertEqual(declared_types.type_words("number | null"),
                         {"int", "float", "NoneType"})

    def test_a_type_written_beside_its_explanation_is_read_to_the_em_dash(self):
        self.assertEqual(
            declared_types.type_words("string — the declared role, or `\"\"`"),
            {"str"})

    def test_an_enum_declares_nothing(self):
        """`` `P0` \\| `P1` \\| `P2` `` is a *Meaning* cell. A reader that took
        it for a type would declare three types no `type().__name__` produces
        and fail every row it touched."""
        self.assertEqual(declared_types.type_words("`P0` | `P1` | `P2`"), set())

    def test_prose_declares_nothing(self):
        self.assertEqual(
            declared_types.type_words("the `RX-NNN` `risk-add` minted"), set())

    def test_one_unknown_word_voids_the_whole_cell(self):
        """Never a partial reading: `string | timestamp` is a page this file
        does not understand, and half of it is worse than none of it."""
        self.assertEqual(declared_types.type_words("string | timestamp"), set())


class TestTheDeclaredArmRefusesTheWrongBranch(unittest.TestCase):
    """Verification 3 and 4, as tests rather than as a paragraph. Both run
    against a page and a payload built here, so neither depends on Perry's own
    board holding a particular row today."""

    PAGE = ("# `demo list --json`\n\n"
            "### A row\n\n"
            "| Key | Type | Meaning |\n|---|---|---|\n"
            "| `id` | string | the row |\n"
            "| `n` | int | a count, never absent |\n"
            "| `age_days` | int \\| null | `today − opened` |\n")

    def declared_for(self, payload):
        boxes = parity.containers(parity.paths(payload),
                                  parity.empty_lists(payload))
        return declared_types.declared(self.PAGE, boxes)

    def off_contract(self, payload):
        declared = self.declared_for(payload)
        live = shape(payload)
        return sorted(key for key, allowed in declared.items()
                      if key in live and types(live[key]) - allowed)

    def test_a_key_declared_int_that_returns_null_is_red(self):
        good = {"rows": [{"id": "a", "n": 1, "age_days": 3}]}
        self.assertEqual(self.declared_for(good),
                         {"rows[].id": {"str"}, "rows[].n": {"int"},
                          "rows[].age_days": {"int", "NoneType"}})
        self.assertEqual(self.off_contract(good), [])
        broken = {"rows": [{"id": "a", "n": None, "age_days": 3}]}
        self.assertEqual(self.off_contract(broken), ["rows[].n"])

    def test_a_union_is_green_on_either_branch_and_on_both(self):
        for rows in ([{"id": "a", "n": 1, "age_days": 3}],
                     [{"id": "a", "n": 1, "age_days": None}],
                     [{"id": "a", "n": 1, "age_days": None},
                      {"id": "b", "n": 2, "age_days": 3}]):
            with self.subTest(rows=rows):
                self.assertEqual(self.off_contract({"rows": rows}), [])

    def test_the_union_is_caught_on_a_later_element_too(self):
        """Element zero is not the only row judged against the page either."""
        rows = [{"id": "a", "n": 1, "age_days": 3},
                {"id": "b", "n": None, "age_days": 3}]
        self.assertEqual(self.off_contract({"rows": rows}), ["rows[].n"])


# Recording is its own entry, ABOVE the canonical one, so the file still ends
# with exactly `if __name__ == "__main__": unittest.main()`. `test_claims`
# requires that tail and was right to: a file whose last statement is anything
# else can run directly, skip its tests and still report OK. It caught this.
if __name__ == "__main__" and "--record" in sys.argv:
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    BASELINE.write_text(json.dumps(capture(), indent=2, sort_keys=True))
    print(f"recorded {BASELINE}")
    sys.exit(0)


if __name__ == "__main__":
    unittest.main()
