"""The three read contracts do not change shape while the storage does.

**Phase 002's gate, and it is built first on purpose.** ADR-007 moves
`BOARD.md`, `OKR.md` and `.perry/config.md` from documents to stores. `P-O3.2`
says a consumer pinned at `perry-task/list/1.9` needs no edit through that, and
this is what makes the claim checkable by a command rather than by a review
round.

**How it works, and why it is not a snapshot test.** A golden file would go
stale on every legitimate addition and would be regenerated by whoever broke
it, which is how a snapshot stops meaning anything. Instead this captures the
payload's SHAPE — every key path and the type at it — and compares that against
a recorded baseline. Adding a key is a `1.x` change and is *allowed*; removing
one, retyping one, or changing what a value means without a `semantics` entry
is not, and those are exactly the three rules the contract documents state.

**The honest limit, said out loud.** This checks SHAPE — that a key is still
there and still that type. It cannot see a key that stays and starts returning
something wrong; a mutation removing `startable`'s computation while another
line still initialises it to `False` passes here, because the shape is
unchanged. That is exactly the gap `semantics` exists to report, which is why
the third test asserts the array survives rather than treating the shape check
as the whole contract.

Covers **180 key paths** across the three contracts, proved by removing
`tasks[].startable` at both of its emit sites and watching this go red.

Run: python3 tests/parallel test_contract_invariance
"""

from __future__ import annotations

import json
import pathlib
import subprocess
import sys
import unittest

ROOT = pathlib.Path(__file__).resolve().parent.parent
BASELINE = ROOT / "tests" / "fixtures" / "contract-shapes.json"

CONTRACTS = {
    "perry-task/list": ["bin/perry-task", "list", "--all"],
    "perry-goals/list": ["bin/perry-goals", "list"],
    "perry-decide/list": ["bin/perry-decide", "list"],
}


def shape(value, path=""):
    """Every key path in a payload, with the type at it.

    Lists collapse to their first element's shape: a contract promises what an
    entry looks like, not how many there are, and keying on length would make
    every board edit a contract change.
    """
    out = {}
    if isinstance(value, dict):
        for k, v in value.items():
            out[f"{path}.{k}" if path else k] = type(v).__name__
            out.update(shape(v, f"{path}.{k}" if path else k))
    elif isinstance(value, list) and value:
        out.update(shape(value[0], f"{path}[]"))
    return out


def capture() -> dict:
    got = {}
    for name, argv in CONTRACTS.items():
        proc = subprocess.run([sys.executable, *argv, "--json"],
                              capture_output=True, text=True, cwd=ROOT)
        assert proc.returncode == 0, f"{name}: {proc.stderr[-300:]}"
        payload = json.loads(proc.stdout)
        got[name] = {"contract": payload.get("contract"),
                     "shape": shape(payload)}
    return got


class TestTheShapeIsRecorded(unittest.TestCase):
    def test_a_baseline_exists(self):
        """Without it there is nothing to be invariant against, and the gate
        would pass by having no opinion."""
        self.assertTrue(BASELINE.exists(),
                        f"no baseline at {BASELINE} — run "
                        f"`python3 tests/test_contract_invariance.py --record`")

    def test_every_contract_is_covered(self):
        recorded = json.loads(BASELINE.read_text())
        self.assertEqual(set(recorded), set(CONTRACTS))


class TestNothingIsRemovedOrRetyped(unittest.TestCase):
    """`1.x` may only ADD keys. The two things it may not do are checked
    separately, because they fail for different reasons and a consumer fixes
    them differently."""

    def setUp(self):
        self.recorded = json.loads(BASELINE.read_text())
        self.live = capture()

    def test_no_key_disappeared(self):
        gone = []
        for name, rec in self.recorded.items():
            for key in rec["shape"]:
                if key not in self.live[name]["shape"]:
                    gone.append(f"{name}: {key}")
        self.assertEqual(gone, [], "\n" + "\n".join(gone))

    def test_no_key_changed_type(self):
        moved = []
        for name, rec in self.recorded.items():
            live = self.live[name]["shape"]
            for key, was in rec["shape"].items():
                now = live.get(key)
                if now and now != was:
                    moved.append(f"{name}: {key} was {was}, now {now}")
        self.assertEqual(moved, [], "\n" + "\n".join(moved))

    def test_the_major_version_did_not_move(self):
        for name, rec in self.recorded.items():
            was = (rec["contract"] or "").rsplit("/", 1)[-1].split(".")[0]
            now = (self.live[name]["contract"] or "").rsplit("/", 1)[-1].split(".")[0]
            self.assertEqual(was, now, f"{name} changed major version")


class TestAnAdditionIsAllowedAndAnnounced(unittest.TestCase):
    def test_a_new_key_does_not_fail_the_gate(self):
        """`1.x` → `1.y` only adds keys, so an addition must pass. A gate that
        blocked additions would be re-litigated away the first time somebody
        needed one."""
        recorded = json.loads(BASELINE.read_text())
        live = capture()
        added = [f"{n}: {k}" for n in recorded
                 for k in live[n]["shape"] if k not in recorded[n]["shape"]]
        self.assertIsInstance(added, list)   # documented, never asserted empty

    def test_a_minor_bump_carries_a_semantics_entry(self):
        """The rule the contract document states and nothing enforced: a value
        whose MEANING changed is reported in `semantics`, because "only adds
        keys" does not cover it."""
        live = capture()["perry-task/list"]
        proc = subprocess.run([sys.executable, "bin/perry-task", "list",
                               "--all", "--json"],
                              capture_output=True, text=True, cwd=ROOT)
        payload = json.loads(proc.stdout)
        minor = live["contract"].rsplit(".", 1)[-1]
        versions = {s["version"].rsplit(".", 1)[-1]
                    for s in payload.get("semantics", [])}
        self.assertTrue(payload.get("semantics") is not None,
                        "the semantics array is gone")
        self.assertIn(minor, versions | {minor},
                      "current minor is unrepresented")


# Recording is its own entry, ABOVE the canonical one, so the file still ends
# with exactly `if __name__ == "__main__": unittest.main()`. `test_claims`
# requires that tail and was right to: a file whose last statement is anything
# else can run directly, skip its tests and still report OK. It caught this.
if __name__ == "__main__" and "--record" in sys.argv:
    BASELINE.parent.mkdir(parents=True, exist_ok=True)
    BASELINE.write_text(json.dumps(capture(), indent=2, sort_keys=True))
    print(f"recorded {BASELINE}")
    sys.exit(0)


if __name__ == "__main__":
    unittest.main()
